# Fundamental Concepts of Tensor using TensorFlow

- Introduction to Tensor
- Getting Information from Tensors
- Manipulating Tensors
- Tensors & Numpy
- Using @tf.function (way to speed up regular Python function)
- Using GPUs with TensorFlow (or TPUs)
- Exercises

<hr>

## Introduction to Tensor

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.13.0


### Creating Tensor with `tf.constant`

In [4]:
# create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# check the number of dimension of a tensor

scalar.ndim

0

In [6]:
# create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
# check dimension of vector
vector.ndim

1

In [8]:
# create a matrix

matrix = tf.constant([[10,7],
                     [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [9]:
matrix.ndim

2

In [11]:
# create another matrix with specified dtype

matrix_1 = tf.constant([[4.,8.],
                        [6.,3],
                        [10.,7]], dtype=tf.float16)

In [12]:
matrix_1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 4.,  8.],
       [ 6.,  3.],
       [10.,  7.]], dtype=float16)>

In [13]:
matrix_1.ndim

2

In [14]:
# Create a tensor

tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                        [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [15]:
tensor.ndim

3

**NOTE:**
- Scalar: has zero (0) dimension. That is, it is a single number.
- Vector: has one dimension. A number with direction (e.g wind speed and direction).
- Matrix: has two dimension. It is a 2D array of numbers.
- Tensor: it is an `n-dimensional` array. It is collection of matrices.

**The `n` can be any number. A 0-dimensional tensor is a scalar. A 1-dimensional tensor is a vector. A two dimensional tensor is a Matrix**