# Basic Tensor Operations
<hr>

`+` `-` `*` `/`

In [1]:
import tensorflow as tf

In [2]:
# you  can add values to a tensor using the additin operation

tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [3]:
# multiplication 

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [4]:
# subtraction

tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

`tf.math`

In [5]:
# we can use the tensorflow built in func

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [8]:
# division

tensor / 3

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.33333333, 2.33333333],
       [1.        , 1.33333333]])>

# Matrix Multiplication with Tensor
<hr>

In machine learning, matrix multiplication is one of the most common tensor 