# Basic Tensor Operations
<hr>

`+` `-` `*` `/` - Element-wise operation

In [1]:
import tensorflow as tf

In [2]:
# you  can add values to a tensor using the additin operation

tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [3]:
# multiplication 

tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [4]:
# subtraction

tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

`tf.math`

In [5]:
# we can use the tensorflow built in func

tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [8]:
# division

tensor / 3

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[3.33333333, 2.33333333],
       [1.        , 1.33333333]])>

# Matrix Multiplication with Tensor
<hr>

In machine learning, matrix multiplication is one of the most common tensor operations.

`tf.matmul`

In [9]:
# matrix multiplication 

tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [10]:
a = tf.constant([[1, 2, 5],[7, 2, 1], [3, 3, 3]])
b = tf.constant([[3, 5], [6, 7], [1, 8]])

In [11]:
a,b

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]])>)

In [12]:
# matrix multiplication

tf.matmul(a,b)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

`@` operator

In [13]:
# you can also use @ operation for matrix multiplication

a@b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]])>

### Tensor multiplication of incompatible size

There are two rules our tensor needs to fulfill if we are going to matrix multiply.

1. The **inner** dimension must match
2. The resulting matrix has the shape of the **outer** dimensions

![rule](../images/matrix%20multiplication.JPG)

In [15]:
X = tf.constant([[1, 2],[3, 4], [5, 6]])
Y = tf.constant([[7, 8],[9, 10],[11, 12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

**Transpose Vs Reshape**

In [19]:
tf.matmul(X,Y, transpose_b=True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [20]:
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

**NOTE:**
- You can use `tf.transpose` 
- Beware of reshaping your tensor
- Reshaping reshuffles the element the original tensor while transpose flip the axis.
- Make sure you use the transpose.

## The dot product

Matrix multiplication is also referred to the dot product.

`tf.matmul()`, `tf.tensordot()`

In [21]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [24]:
# perform the dot product on X and Y

tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [25]:
tf.tensordot(X,tf.transpose(Y),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>