# Tensor Manipulations
<hr>

- Change datatype of tensor
- Aggregating tensor

In [1]:
import tensorflow as tf

## Change datatype

In [6]:
# change the datatype of a tensor

B = tf.constant([1.7, 7.4])
B.dtype

# by default it is always 32bits. By keeping certain parts of the model in the
# 32 bit type for numerical stability and metrics accuracy.

tf.float32

In [7]:
C = tf.constant([5, 10])
C.dtype

tf.int32

`tf.cast()`

In [8]:
# change from float32 to float16 (reduce precision)
# modern accelerators can run operations faster in the 16-bit dtypes

D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [9]:
# change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 5., 10.], dtype=float32)>

## Aggregating tensors

Aggregating tensors = condensing them from multiple values down to smaller amount of values

- Getting absolute value
- Getting mean value
- Getting minimum value
- Getting maximum value

In [10]:
# get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [11]:
# turn negative to positive
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [15]:
# create random tensor
import numpy as np

E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 1, 32, 99, 93, 74,  1, 33, 71, 32, 77, 65, 56, 74, 52, 69, 89, 47,
       17, 37, 80, 83, 36, 57, 88, 43, 41, 30, 28,  4, 28, 15, 21, 58, 42,
       34, 17, 64, 16, 47, 44, 74, 85, 98, 74, 71, 98, 81, 94, 71, 33])>

In [17]:
tf.size(E), tf.shape(E), E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([50])>,
 1)

`tf.reduce_min()`

In [18]:
# get the min

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

`tf.reduce_max()`

In [19]:
# get the maximum value
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

`tf.reduce_mean()`

In [20]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=53>

`tf.reduce_sum()`

In [21]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2674>

**Note:** To find the standard deviation and variance, you may have to import `tensorflow_probability` as in:

```py
import tensorflow_probability as tfp
```

In [29]:
# another way to find standard deviation

tf.math.reduce_std(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=27.71298612564153>

In [31]:
# another way to find variance of a tensor

tf.math.reduce_variance(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=768.0096000000001>

**N.B:** Without converting the dytpe from `int` to `float` it won't work!

## Positional Max and Min