# Tensor Manipulations
<hr>

- <a href="#dtype">Change datatype of tensor</a>
- <a href="#aggregate">Aggregating tensor</a>
- <a href="#position">Positional max and min</a>
- <a href="#squeeze">Squeezing tensor</a>
- <a href="#one-hot">One-hot encoding</a>

In [1]:
import tensorflow as tf

## Change datatype
<div id='dtype'></div>

In [6]:
# change the datatype of a tensor

B = tf.constant([1.7, 7.4])
B.dtype

# by default it is always 32bits. By keeping certain parts of the model in the
# 32 bit type for numerical stability and metrics accuracy.

tf.float32

In [7]:
C = tf.constant([5, 10])
C.dtype

tf.int32

`tf.cast()`

In [8]:
# change from float32 to float16 (reduce precision)
# modern accelerators can run operations faster in the 16-bit dtypes

D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [9]:
# change from int32 to float32

E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 5., 10.], dtype=float32)>

## Aggregating tensors
<div id='aggregate'></div>

Aggregating tensors = condensing them from multiple values down to smaller amount of values

- Getting absolute value
- Getting mean value
- Getting minimum value
- Getting maximum value

In [10]:
# get the absolute values

D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [11]:
# turn negative to positive
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [15]:
# create random tensor
import numpy as np

E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 1, 32, 99, 93, 74,  1, 33, 71, 32, 77, 65, 56, 74, 52, 69, 89, 47,
       17, 37, 80, 83, 36, 57, 88, 43, 41, 30, 28,  4, 28, 15, 21, 58, 42,
       34, 17, 64, 16, 47, 44, 74, 85, 98, 74, 71, 98, 81, 94, 71, 33])>

In [17]:
tf.size(E), tf.shape(E), E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([50])>,
 1)

`tf.reduce_min()`

In [18]:
# get the min

tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

`tf.reduce_max()`

In [19]:
# get the maximum value
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

`tf.reduce_mean()`

In [20]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=53>

`tf.reduce_sum()`

In [21]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2674>

**Note:** To find the standard deviation and variance, you may have to import `tensorflow_probability` as in:

```py
import tensorflow_probability as tfp
```

In [29]:
# another way to find standard deviation

tf.math.reduce_std(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=27.71298612564153>

In [31]:
# another way to find variance of a tensor

tf.math.reduce_variance(tf.cast(E, dtype=tf.float64))

<tf.Tensor: shape=(), dtype=float64, numpy=768.0096000000001>

**N.B:** Without converting the dytpe from `int` to `float` it won't work!

<div id='position'></div>

## Positional Max and Min

At what index the max or min occurs using `tf.argmax()` and `tf.argmin()` respectively.

In [33]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [34]:
# find the position at max

tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [35]:
# index on the largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [36]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [37]:
# check for equality

assert F[tf.argmax(F)] == tf.reduce_max(F)
# if no error, it is equal otherwise, it is not.

In [38]:
# find the positional minimum

tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [39]:
# find minimum using positional mininum

F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [40]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

<div id='squeeze'></div>

## Squeezing tensor

Removing dimension of size 1 from the shape of a tensor.

In [43]:
# create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [44]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [45]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [46]:
G_squeezed.shape

TensorShape([50])

<div id='one-hot'></div>

## One-Hot Encoding Tensor

It is a form of numerical encoding.

In [47]:
# create list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [51]:
# specify custom value for one hot encoding

tf.one_hot(some_list,depth=4,on_value='one', off_value='zero')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'one', b'zero', b'zero', b'zero'],
       [b'zero', b'one', b'zero', b'zero'],
       [b'zero', b'zero', b'one', b'zero'],
       [b'zero', b'zero', b'zero', b'one']], dtype=object)>