# Tensor and Numpy Compatibility

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
# create a tensor directly from NumPy array

J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [5]:
# convert tensor back to Numpy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [8]:
# another method

J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [10]:
# default types of each are slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3., 7., 10.])

# check the dtype
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

**Note:** One of the main difference between a TensorFlow tensor and a NumPy array is that a Tensorflow tensor has the datatype of **32-bits** compared to Numpy which has **64-bits**. Hence, TensorFlow tensor has faster numerical processing.

## Access to GPU

In [14]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [13]:
tf.config.list_physical_devices("GPU")

[]

Since the output about is an empty list, that means no GPU is found. You can access GPU on `Google Colab`