# Improving Neural Network Regression
<hr>

**Goal:**
- Given the data X = -7.0, -4.0, -1.0, 2.0, 5.0, 8.0, 11.0, 14.0
- y = 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0
- The relationship is $y = X + 10$
- Predict y if X = 17.0
- Improve the prediction for accuracy

<a href="#how">How to improve the model</a>

In [1]:
import tensorflow as tf

In [2]:
X = tf.constant([-7.0, -4.0, -1.0, 2.0, 5.0, 8.0, 11.0, 14.0])
y = tf.constant([3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0])

In [3]:
X,y

(<tf.Tensor: shape=(8,), dtype=float32, numpy=array([-7., -4., -1.,  2.,  5.,  8., 11., 14.], dtype=float32)>,
 <tf.Tensor: shape=(8,), dtype=float32, numpy=array([ 3.,  6.,  9., 12., 15., 18., 21., 24.], dtype=float32)>)

In [4]:
# Set random seed
tf.random.set_seed(42)

# 1. Create a model using Sequential API
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=['mae'])

model.fit(X,y,epochs=5)

Epoch 1/5
1/1 [==============================] - 1s 711ms/step - loss: 17.2799 - mae: 17.2799
Epoch 2/5
1/1 [==============================] - 0s 10ms/step - loss: 16.9987 - mae: 16.9987
Epoch 3/5
1/1 [==============================] - 0s 9ms/step - loss: 16.7174 - mae: 16.7174
Epoch 4/5
1/1 [==============================] - 0s 10ms/step - loss: 16.4362 - mae: 16.4362
Epoch 5/5
1/1 [==============================] - 0s 9ms/step - loss: 16.1549 - mae: 16.1549


In [5]:
y_pred = model.predict([17.0])
y_pred

1/1 [==============================] - 0s 194ms/step


array([[-10.16827]], dtype=float32)

In [6]:
# the model is very bad
y_pred + 17

array([[6.83173]], dtype=float32)

<div id="how"></div>

## Improving a model

A model can be improved by altering the steps in creating it. 

**Creating a model:** You might:
- add more layers
- increase the number of hidden units (neurons)
- change the activation function of each layer.
        
**Compiling a model:** You might:
- change the optimization function
- perhaps change the *learning rate* of optimizer
        
**Fitting a model:** You might:
- fit a model for more **epochs** (leave it training for longer)
- give the model more examples to learn from.

### Improve it by increasing the epochs

In [7]:
tf.random.set_seed(42)
# 1. Create the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])

# 2. Compile model
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=['mae'])

# 3. fit the model
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 271ms/step - loss: 16.3952 - mae: 16.3952
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 16.1139 - mae: 16.1139
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 15.8327 - mae: 15.8327
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 15.5514 - mae: 15.5514
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 15.2702 - mae: 15.2702
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 14.9889 - mae: 14.9889
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 14.7826 - mae: 14.7826
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 14.6501 - mae: 14.6501
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 14.5176 - mae: 14.5176
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 14.3851 - mae: 14.3851
Epoch 11/100
1/1 [==============================] - 0s 5m

1/1 [==============================] - 0s 7ms/step - loss: 6.9000 - mae: 6.9000
Epoch 89/100
1/1 [==============================] - 0s 7ms/step - loss: 6.8944 - mae: 6.8944
Epoch 90/100
1/1 [==============================] - 0s 7ms/step - loss: 6.8888 - mae: 6.8888
Epoch 91/100
1/1 [==============================] - 0s 6ms/step - loss: 6.8831 - mae: 6.8831
Epoch 92/100
1/1 [==============================] - 0s 6ms/step - loss: 6.8775 - mae: 6.8775
Epoch 93/100
1/1 [==============================] - 0s 6ms/step - loss: 6.8719 - mae: 6.8719
Epoch 94/100
1/1 [==============================] - 0s 7ms/step - loss: 6.8663 - mae: 6.8663
Epoch 95/100
1/1 [==============================] - 0s 7ms/step - loss: 6.8606 - mae: 6.8606
Epoch 96/100
1/1 [==============================] - 0s 6ms/step - loss: 6.8550 - mae: 6.8550
Epoch 97/100
1/1 [==============================] - 0s 5ms/step - loss: 6.8494 - mae: 6.8494
Epoch 98/100
1/1 [==============================] - 0s 7ms/step - loss: 6.8438 - ma

In [8]:
y_pred = model.predict([17.0])
y_pred

1/1 [==============================] - 0s 63ms/step


array([[29.554056]], dtype=float32)

### Improve the model by changing the optimizer

In [9]:
# set seed
tf.random.set_seed(42)

# 1. Create the model
model =  tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])

# 2. Compile the model
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.Adam(),
              metrics=['mae'])

# 3. Fit model
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 343ms/step - loss: 9.2575 - mae: 9.2575
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 9.2530 - mae: 9.2530
Epoch 3/100
1/1 [==============================] - 0s 6ms/step - loss: 9.2485 - mae: 9.2485
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 9.2440 - mae: 9.2440
Epoch 5/100
1/1 [==============================] - 0s 5ms/step - loss: 9.2395 - mae: 9.2395
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 9.2350 - mae: 9.2350
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 9.2305 - mae: 9.2305
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 9.2260 - mae: 9.2260
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 9.2215 - mae: 9.2215
Epoch 10/100
1/1 [==============================] - 0s 7ms/step - loss: 9.2170 - mae: 9.2170
Epoch 11/100
1/1 [==============================] - 0s 7ms/step - loss: 9.212

1/1 [==============================] - 0s 8ms/step - loss: 8.8615 - mae: 8.8615
Epoch 90/100
1/1 [==============================] - 0s 7ms/step - loss: 8.8570 - mae: 8.8570
Epoch 91/100
1/1 [==============================] - 0s 6ms/step - loss: 8.8525 - mae: 8.8525
Epoch 92/100
1/1 [==============================] - 0s 7ms/step - loss: 8.8480 - mae: 8.8480
Epoch 93/100
1/1 [==============================] - 0s 8ms/step - loss: 8.8435 - mae: 8.8435
Epoch 94/100
1/1 [==============================] - 0s 7ms/step - loss: 8.8390 - mae: 8.8390
Epoch 95/100
1/1 [==============================] - 0s 6ms/step - loss: 8.8345 - mae: 8.8345
Epoch 96/100
1/1 [==============================] - 0s 7ms/step - loss: 8.8300 - mae: 8.8300
Epoch 97/100
1/1 [==============================] - 0s 6ms/step - loss: 8.8255 - mae: 8.8255
Epoch 98/100
1/1 [==============================] - 0s 9ms/step - loss: 8.8210 - mae: 8.8210
Epoch 99/100
1/1 [==============================] - 0s 10ms/step - loss: 8.8165 - m

In [10]:
y_pred = model.predict([17.0])
y_pred

1/1 [==============================] - 0s 63ms/step


array([[22.406668]], dtype=float32)

### Improve the model by adding extra hidden layer


In [28]:
# 1. Create the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1,input_shape=(1,)),
    tf.keras.layers.Dense(100, activation='relu'),
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
model.compile(loss='mae',
              optimizer=tf.keras.optimizers.SGD(),
              metrics=['mae'])

# 3. Fit model
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 367ms/step - loss: 14.1836 - mae: 14.1836
Epoch 2/100
1/1 [==============================] - 0s 17ms/step - loss: 13.8948 - mae: 13.8948
Epoch 3/100
1/1 [==============================] - 0s 8ms/step - loss: 13.6186 - mae: 13.6186
Epoch 4/100
1/1 [==============================] - 0s 6ms/step - loss: 13.3479 - mae: 13.3479
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 13.0757 - mae: 13.0757
Epoch 6/100
1/1 [==============================] - 0s 6ms/step - loss: 12.7953 - mae: 12.7953
Epoch 7/100
1/1 [==============================] - 0s 6ms/step - loss: 12.4994 - mae: 12.4994
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 12.1804 - mae: 12.1804
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 11.8343 - mae: 11.8343
Epoch 10/100
1/1 [==============================] - 0s 5ms/step - loss: 11.4466 - mae: 11.4466
Epoch 11/100
1/1 [==============================] - 0s 6

1/1 [==============================] - 0s 7ms/step - loss: 3.7211 - mae: 3.7211
Epoch 89/100
1/1 [==============================] - 0s 7ms/step - loss: 3.6005 - mae: 3.6005
Epoch 90/100
1/1 [==============================] - 0s 7ms/step - loss: 3.6625 - mae: 3.6625
Epoch 91/100
1/1 [==============================] - 0s 8ms/step - loss: 3.6185 - mae: 3.6185
Epoch 92/100
1/1 [==============================] - 0s 6ms/step - loss: 3.6201 - mae: 3.6201
Epoch 93/100
1/1 [==============================] - 0s 11ms/step - loss: 3.6570 - mae: 3.6570
Epoch 94/100
1/1 [==============================] - 0s 8ms/step - loss: 3.5639 - mae: 3.5639
Epoch 95/100
1/1 [==============================] - 0s 7ms/step - loss: 3.6760 - mae: 3.6760
Epoch 96/100
1/1 [==============================] - 0s 6ms/step - loss: 3.5574 - mae: 3.5574
Epoch 97/100
1/1 [==============================] - 0s 5ms/step - loss: 3.6497 - mae: 3.6497
Epoch 98/100
1/1 [==============================] - 0s 6ms/step - loss: 3.5758 - m

In [29]:
model.predict([17.0])

1/1 [==============================] - 0s 76ms/step


array([[31.263432]], dtype=float32)

### Improving by Adding hidden layer and decreasing neuron

In [40]:
# 1. Create the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1,input_shape=(1,)),
    tf.keras.layers.Dense(10, activation=None),
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
model.compile(loss='mae',
              optimizer=tf.keras.optimizers.SGD(),
              metrics=['mae'])

# 3. Fit model
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 369ms/step - loss: 14.3601 - mae: 14.3601
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 13.4278 - mae: 13.4278
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 12.5091 - mae: 12.5091
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 11.5741 - mae: 11.5741
Epoch 5/100
1/1 [==============================] - 0s 6ms/step - loss: 10.5928 - mae: 10.5928
Epoch 6/100
1/1 [==============================] - 0s 7ms/step - loss: 9.5327 - mae: 9.5327
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 8.3573 - mae: 8.3573
Epoch 8/100
1/1 [==============================] - 0s 5ms/step - loss: 7.2713 - mae: 7.2713
Epoch 9/100
1/1 [==============================] - 0s 6ms/step - loss: 7.2391 - mae: 7.2391
Epoch 10/100
1/1 [==============================] - 0s 6ms/step - loss: 7.2067 - mae: 7.2067
Epoch 11/100
1/1 [==============================] - 0s 7ms/step - l

1/1 [==============================] - 0s 7ms/step - loss: 4.3170 - mae: 4.3170
Epoch 90/100
1/1 [==============================] - 0s 8ms/step - loss: 4.4441 - mae: 4.4441
Epoch 91/100
1/1 [==============================] - 0s 6ms/step - loss: 4.6139 - mae: 4.6139
Epoch 92/100
1/1 [==============================] - 0s 7ms/step - loss: 4.5702 - mae: 4.5702
Epoch 93/100
1/1 [==============================] - 0s 7ms/step - loss: 4.3063 - mae: 4.3063
Epoch 94/100
1/1 [==============================] - 0s 8ms/step - loss: 3.9964 - mae: 3.9964
Epoch 95/100
1/1 [==============================] - 0s 6ms/step - loss: 3.9041 - mae: 3.9041
Epoch 96/100
1/1 [==============================] - 0s 8ms/step - loss: 3.9164 - mae: 3.9164
Epoch 97/100
1/1 [==============================] - 0s 5ms/step - loss: 4.0659 - mae: 4.0659
Epoch 98/100
1/1 [==============================] - 0s 8ms/step - loss: 4.2354 - mae: 4.2354
Epoch 99/100
1/1 [==============================] - 0s 5ms/step - loss: 4.1470 - ma

In [41]:
model.predict([17.0])

1/1 [==============================] - 0s 70ms/step


array([[28.65286]], dtype=float32)

### Improving by adding layer & changing the learning rate (0.01)

In [56]:
# 1. Create the model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1,input_shape=(1,)),
    tf.keras.layers.Dense(50, activation=None),
    tf.keras.layers.Dense(1)
])

# 2. Compile the model
model.compile(loss='mae',
              optimizer=tf.keras.optimizers.Adam(0.01),
              metrics=['mae'])

# 3. Fit model
model.fit(X,y,epochs=100)

Epoch 1/100
1/1 [==============================] - 1s 573ms/step - loss: 13.8818 - mae: 13.8818
Epoch 2/100
1/1 [==============================] - 0s 8ms/step - loss: 13.4218 - mae: 13.4218
Epoch 3/100
1/1 [==============================] - 0s 7ms/step - loss: 12.9802 - mae: 12.9802
Epoch 4/100
1/1 [==============================] - 0s 7ms/step - loss: 12.5425 - mae: 12.5425
Epoch 5/100
1/1 [==============================] - 0s 7ms/step - loss: 12.0967 - mae: 12.0967
Epoch 6/100
1/1 [==============================] - 0s 9ms/step - loss: 11.6379 - mae: 11.6379
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 11.1626 - mae: 11.1626
Epoch 8/100
1/1 [==============================] - 0s 11ms/step - loss: 10.6679 - mae: 10.6679
Epoch 9/100
1/1 [==============================] - 0s 11ms/step - loss: 10.1511 - mae: 10.1511
Epoch 10/100
1/1 [==============================] - 0s 12ms/step - loss: 9.6090 - mae: 9.6090
Epoch 11/100
1/1 [==============================] - 0s 

1/1 [==============================] - 0s 7ms/step - loss: 0.1773 - mae: 0.1773
Epoch 89/100
1/1 [==============================] - 0s 7ms/step - loss: 0.1270 - mae: 0.1270
Epoch 90/100
1/1 [==============================] - 0s 7ms/step - loss: 0.0651 - mae: 0.0651
Epoch 91/100
1/1 [==============================] - 0s 7ms/step - loss: 0.0440 - mae: 0.0440
Epoch 92/100
1/1 [==============================] - 0s 6ms/step - loss: 0.1703 - mae: 0.1703
Epoch 93/100
1/1 [==============================] - 0s 6ms/step - loss: 0.1853 - mae: 0.1853
Epoch 94/100
1/1 [==============================] - 0s 6ms/step - loss: 0.1390 - mae: 0.1390
Epoch 95/100
1/1 [==============================] - 0s 7ms/step - loss: 0.1598 - mae: 0.1598
Epoch 96/100
1/1 [==============================] - 0s 6ms/step - loss: 0.0634 - mae: 0.0634
Epoch 97/100
1/1 [==============================] - 0s 7ms/step - loss: 0.0703 - mae: 0.0703
Epoch 98/100
1/1 [==============================] - 0s 6ms/step - loss: 0.1011 - ma

In [58]:
y_pred = model.predict([17.0])
y_pred

1/1 [==============================] - 0s 41ms/step


array([[26.664837]], dtype=float32)