# Improving Neural Network Regression
<hr>

**Goal:**
- Given the data X = -7.0, -4.0, -1.0, 2.0, 5.0, 8.0, 11.0, 14.0
- y = 3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0
- The relationship is $y = X + 10$
- Predict y if X = 17.0
- Improve the prediction for accuracy

In [1]:
import tensorflow as tf

In [2]:
X = tf.constant([-7.0, -4.0, -1.0, 2.0, 5.0, 8.0, 11.0, 14.0])
y = tf.constant([3.0, 6.0, 9.0, 12.0, 15.0, 18.0, 21.0, 24.0])

In [3]:
X,y

(<tf.Tensor: shape=(8,), dtype=float32, numpy=array([-7., -4., -1.,  2.,  5.,  8., 11., 14.], dtype=float32)>,
 <tf.Tensor: shape=(8,), dtype=float32, numpy=array([ 3.,  6.,  9., 12., 15., 18., 21., 24.], dtype=float32)>)

In [4]:
# Set random seed
tf.random.set_seed(42)

# 1. Create a model using Sequential API
model = tf.keras.Sequential([
    tf.keras.layers.Dense(1, input_shape=(1,))
])

model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizers.SGD(),
              metrics=['mae'])

model.fit(X,y,epochs=5)

Epoch 1/5
1/1 [==============================] - 1s 711ms/step - loss: 17.2799 - mae: 17.2799
Epoch 2/5
1/1 [==============================] - 0s 10ms/step - loss: 16.9987 - mae: 16.9987
Epoch 3/5
1/1 [==============================] - 0s 9ms/step - loss: 16.7174 - mae: 16.7174
Epoch 4/5
1/1 [==============================] - 0s 10ms/step - loss: 16.4362 - mae: 16.4362
Epoch 5/5
1/1 [==============================] - 0s 9ms/step - loss: 16.1549 - mae: 16.1549


In [5]:
y_pred = model.predict([17.0])
y_pred

1/1 [==============================] - 0s 194ms/step


array([[-10.16827]], dtype=float32)

In [6]:
# the model is very bad
y_pred + 17

array([[6.83173]], dtype=float32)

### Improving a model

A model can be improved by altering the steps in creating it. 

**Creating a model:** You might:
- add more layers
- increase the number of hidden units (neurons)
- change the activation function of each layer.
        
**Compiling a model:** You might:
- change the optimization function
- perhaps change the *learning rate* of optimizer
        
**Fitting a model:** You might:
- fit a model for more **epochs** (leave it training for longer)
- give the model more examples to learn from.